### ISSUE TITLE
(SP: 3) Implement Sign up page

### ISSUE THREAD

**Issue by mxrcury** [ArturBekhDEV/Intern-ui#11]
UserStory: #2 
## Description
Add icon and text "Sign up" below, use form component, and add text "Already have an account? Sign in" below.
## Design

![Image](https://github.com/ArturBekhDEV/Intern-ui/assets/90138904/8abc49c7-c8da-4503-a4a6-b97803b87448)

## Acceptance Criteria
- [ ] It should contain icon on the top and "Sign up" title below
- [ ] It should use existing form component
- [ ] It should have text "Already have an account? Sign in" and "Sign in" should be link
- [ ] Add sending data to backend (*using Axios*)
- [ ] Cover by unit tests

**Comment by Olamarx** [comment]
@mxrcury and @ArturBekhDEV I can help you out with this quickly, should I continue?
